### ISSUE TITLE
Incorrect text color in Mailspring email client

### ISSUE THREAD

**Issue by stefanjudis** [buttondown-email/roadmap#852]
Heyoooo, I just received a report that [my newsletter isn't rendered properly in the Mailspring email client](https://twitter.com/dkouvdis/status/1566714873505095680?s=20&t=e-kNQDs2wetzoZUfxpyBCA).

My applied CSS is the following:

```css
div {
  width: 100% !important;
  display: block !important;
  margin-left: auto !important;
  margin-right: auto !important;
}

h1, h2, h3 {
  margin-top: 3em !important;
  font-size: 1.75em;
  line-height: 1.25;
}

.btn {
  display: inline-flex;
  align-items: center;
  line-height: 1.5;
  font-weight: 400;
  font-size: 1em;
  background: #fff;
  color: currentColor;
  border: 2px solid currentColor;
  padding: .375em 1em;
  text-decoration: none;
  border-radius: .125em;
  cursor: pointer;
}

hr {
  margin-top: 2em;
  margin-bottom: 2em;
  border: none;
  border-top: 2px solid #ddd;
}

ul {
  margin-left: 0.5em;
  padding-left: 0;
}

.newsletter-image {
  border: 1px solid #ddd;
  box-shadow: 0 2px 3px #eee;
  border-radius: 4px;
}
```

As I don't see anything messing with text colors here (except the button), I assume this problem exists for all newsletters. :) 

Thanks a bunch. :)
